import type { Metadata } from "next";
import "./globals.css";

import Sidebar from '@/components/Sidebar';

export const metadata: Metadata = {
  title: "MP Fans",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <div className="flex">
      <Sidebar />
      <main className="flex-1 overflow-y-auto bg-zinc-950 px-6 py-10 text-zinc-100">
        {children}
      </main>
    </div>
      </body>
    </html>
  );
}
